# Generated by Django 3.0.2 on 2020-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idown', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('postcode_lookup', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('imageurl', models.CharField(max_length=50)),
                ('largeimageurl', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('openingtimes', models.CharField(max_length=50)),
                ('tickets', models.CharField(max_length=50)),
                ('entryprice', models.CharField(max_length=50)),
                ('eventvisibility', models.CharField(max_length=50)),
            ],
        ),
    ]
