# Generated by Django 3.0.2 on 2020-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='party',
            name='imageurl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='party',
            name='largeimageurl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='party',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
